package io.github.biglv666.statekit.history;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * 默认 JDBC 历史写入实现。
 *
 * <p>创建时机由 AutoConfiguration 控制：仅当 {@code state-kit.history.enabled=true}
 * 且容器存在 {@link DataSource} 时注册。Bean 初始化时执行<b>幂等建表</b>：
 * 先查 {@link DatabaseMetaData}，表或索引已存在则跳过并打日志
 * （不依赖 CREATE INDEX IF NOT EXISTS——MySQL 不支持该语法）。</p>
 *
 * <p>写入走容器的 {@link JdbcTemplate}，无独立事务声明，天然参与 fire 所在事务，
 * 满足「业务回滚历史也回滚」。</p>
 */
public class JdbcHistoryRecorder implements HistoryRecorder {

    private static final Logger log = LoggerFactory.getLogger(JdbcHistoryRecorder.class);

    private final JdbcTemplate jdbcTemplate;
    private final DataSource dataSource;
    private final String tableName;

    public JdbcHistoryRecorder(JdbcTemplate jdbcTemplate, DataSource dataSource, String tableName) {
        this.jdbcTemplate = jdbcTemplate;
        this.dataSource = dataSource;
        this.tableName = tableName;
    }

    /**
     * 初始化：检查并按需创建历史表与索引（幂等，可重复执行）。
     *
     * @throws IllegalStateException DDL 执行失败时抛出，阻止应用带病启动
     */
    public void initialize() {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData meta = connection.getMetaData();
            if (!tableExists(meta, tableName)) {
                jdbcTemplate.execute(createTableSql(meta.getDatabaseProductName()));
                log.info("state-kit 历史表已创建: {}", tableName);
            } else {
                log.debug("state-kit 历史表已存在, 跳过建表: {}", tableName);
            }
            String indexName = "idx_sk_history_machine_entity";
            if (!indexExists(meta, tableName, indexName)) {
                jdbcTemplate.execute("CREATE INDEX " + indexName + " ON " + tableName
                        + " (machine, entity_id, create_time)");
                log.info("state-kit 历史表索引已创建: {}", indexName);
            } else {
                log.debug("state-kit 历史表索引已存在, 跳过: {}", indexName);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("state-kit 历史表初始化失败: " + tableName, e);
        }
    }

    /**
     * 按数据库产品选择自增主键语法：MySQL 用 AUTO_INCREMENT，
     * 其余（H2 / PostgreSQL 等）用标准 GENERATED ... AS IDENTITY。
     */
    private String createTableSql(String databaseProductName) {
        String productName = databaseProductName == null ? "" : databaseProductName.toLowerCase();
        String idColumn = productName.contains("mysql") || productName.contains("mariadb")
                ? "id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY"
                : "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
        return """
                CREATE TABLE IF NOT EXISTS %s (
                    %s,
                    machine     VARCHAR(64)  NOT NULL,
                    entity_id   VARCHAR(64)  NOT NULL,
                    from_state  VARCHAR(64)  NOT NULL,
                    to_state    VARCHAR(64)  NOT NULL,
                    event       VARCHAR(64)  NOT NULL,
                    operator_id VARCHAR(64),
                    trace_id    VARCHAR(64),
                    create_time TIMESTAMP   NOT NULL
                )""".formatted(tableName, idColumn);
    }

    private boolean tableExists(DatabaseMetaData meta, String table) throws SQLException {
        try (ResultSet rs = meta.getTables(null, null, table, new String[]{"TABLE"})) {
            if (rs.next()) {
                return true;
            }
        }
        // 部分驱动按大写存储表名，做一次大写重查
        try (ResultSet rs = meta.getTables(null, null, table.toUpperCase(), new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    private boolean indexExists(DatabaseMetaData meta, String table, String indexName) throws SQLException {
        // 不同数据库对未加引号标识符的大小写处理不同（H2 全大写、MySQL 小写），两种形态都查
        Set<String> names = new LinkedHashSet<>();
        for (String candidate : new String[]{table, table.toUpperCase()}) {
            collectIndexNames(meta, candidate, null, names);
            collectIndexNames(meta, candidate, "PUBLIC", names);
        }
        return names.contains(indexName.toLowerCase());
    }

    private void collectIndexNames(DatabaseMetaData meta, String table, String schema, Set<String> into)
            throws SQLException {
        try (ResultSet rs = meta.getIndexInfo(null, schema, table, false, false)) {
            while (rs.next()) {
                String name = rs.getString("INDEX_NAME");
                if (name != null) {
                    into.add(name.toLowerCase());
                }
            }
        } catch (SQLException ignored) {
            // 个别驱动对特定 schema 参数不支持，忽略后视为索引不存在并尝试重建
        }
    }

    @Override
    public void record(HistoryRecord record) {
        jdbcTemplate.update("""
                        INSERT INTO %s (machine, entity_id, from_state, to_state, event, operator_id, trace_id, create_time)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?)""".formatted(tableName),
                record.getMachine(), record.getEntityId(), record.getFromState(), record.getToState(),
                record.getEvent(), record.getOperatorId(), record.getTraceId(),
                record.getCreateTime() == null ? LocalDateTime.now() : record.getCreateTime());
    }
}
